Repository nextcloud/profiler, pull requests merged in 2023-02, with the labels that each got.

#98 allow exporting profiles from the webui
  src/components/ProfileHeader.vue
Labels: 3. to review

#87 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#86 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#94 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#96 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#108 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
