Repository nextcloud/profiler, pull requests merged in 2024-07, with the labels that each got.

#406 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#408 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#409 Migrate REUSE to TOML format
  .reuse/dep5
  REUSE.toml
Labels: 3. to review

#412 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#411 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#413 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#410 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#405 fix: Improve compatibility with upcoming doctrine/dbal 4.0
  lib/Controller/DatabaseProfilerController.php
Labels: bug

#414 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#415 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#417 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#420 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#418 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#419 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
