Repository nextcloud/profiler, pull requests merged in 2024-02, with the labels that each got.

#323 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#324 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#325 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#326 [stable28] chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#328 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#330 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#332 fix: profiler data and lint
  action/dist/index.js
  action/index.js
Labels: bug, 3. to review

#333 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#334 fix(action): Fix warning about unexpected input
  action.yml
Labels: bug
