Repository nextcloud/profiler, pull requests merged in 2025-08, with the labels that each got.

#586 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#587 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#588 fix(toolbar): Filter out invalid entries in toolbar
  src/views/ProfilerToolbar.vue
Labels: bug, 3. to review

#593 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#594 fix(database-view): Port grouping buttons code to vue3
  src/views/DatabaseProfilerView.vue
Labels: bug

#595 fix(database-view): Fix missing spacing between query number
  src/views/DatabaseProfilerView.vue
Labels: bug

#599 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#601 build: update node and npm engines versions
  package.json
Labels: dependencies

#611 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
